schemaVersion: 2.1.0
metadata:
  name: java-maven-quarkus-lombok
components:
  # - attributes:
  #     app.kubernetes.io/name: tools
  #     che-theia.eclipse.org/vscode-extensions:
  #       - 'https://github.com/redhat-developer/codeready-workspaces-vscode-extensions/releases/download/7.44-che-assets/vscode-quarkus-1.7.0-437.vsix'
  #       - 'https://github.com/redhat-developer/codeready-workspaces-vscode-extensions/releases/download/7.44-che-assets/java-0.82.0-369.vsix'
  #       - 'https://github.com/redhat-developer/codeready-workspaces-vscode-extensions/releases/download/7.44-che-assets/vscode-microprofile-0.1.1-48.vsix'
  #       - 'https://github.com/redhat-developer/codeready-workspaces-vscode-extensions/releases/download/7.44-che-assets/vscode-java-debug-0.26.0.vsix'
  #       - 'https://open-vsx.org/api/vscjava/vscode-java-test/0.28.1/file/vscjava.vscode-java-test-0.28.1.vsix'
  #     che-theia.eclipse.org/vscode-preferences:
  #       java.server.launchMode: Standard
  - name: tools
    container:
      args:
        - sh
        - '-c'
        - '${PLUGIN_REMOTE_ENDPOINT_EXECUTABLE}'
      endpoints:
        - exposure: none
          name: debug
          protocol: tcp
          targetPort: 5005
        - exposure: public
          name: blog-posts-endpoint
          path: /blog/posts
          protocol: http
          targetPort: 8080
      env:
        - name: QUARKUS_HTTP_HOST
          value: 0.0.0.0
      image: 'registry.redhat.io/devspaces/udi-rhel8'
      memoryLimit: 4G
      mountSources: true
      sourceMapping: /projects
      volumeMounts:
        - name: m2
          path: /home/user/.m2
  - container:
      args:
        - '-f'
        - /dev/null
      command:
        - tail
      image: registry.access.redhat.com/ubi8/ubi-minimal
      memoryLimit: 64M
      mountSources: true
      sourceMapping: /projects
    name: ubi-minimal
  - name: m2
    volume:
      size: 1G
# commands:
#   - exec:
#       commandLine: mvn package
#       component: tools
#       group:
#         isDefault: true
#         kind: build
#       workingDir: '${PROJECT_SOURCE}/getting-started'
#     id: package
#   - exec:
#       commandLine: mvn package -Dnative -Dmaven.test.skip -Dquarkus.native.native-image-xmx=2G
#       component: tools
#       group:
#         kind: build
#       label: Package Native
#       workingDir: '${PROJECT_SOURCE}/getting-started'
#     id: package-native
#   - exec:
#       commandLine: 'mvn compile quarkus:dev'
#       component: tools
#       group:
#         isDefault: true
#         kind: run
#       label: Start Development mode (Hot reload + debug)
#       workingDir: '${PROJECT_SOURCE}/getting-started'
#     id: start-dev
#   - exec:
#       commandLine: ./getting-started-1.0.0-SNAPSHOT-runner
#       component: ubi-minimal
#       group:
#         kind: run
#       label: Start Native
#       workingDir: '${PROJECT_SOURCE}/getting-started/target'
#     id: start-native